version: '3.3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper

  cmak:
    image: hlebalbau/kafka-manager:latest
    container_name: cmak
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - zookeeper
      - kafka

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./init-rabbitmq.sh:/init-rabbitmq.sh
    command: ["bash", "-c", "rabbitmq-server & sleep 10 && /init-rabbitmq.sh && tail -f /dev/null"]

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    container_name: payment
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - kafka

  marketplace:
    build:
      context: ./marketplace
      dockerfile: Dockerfile
    container_name: marketplace
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
      - kafka
