spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
      globally_quoted_identifiers: true
    show-sql: true
    format_sql: true
    generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
  rabbitmq:
     host: localhost
     port: 5672
     username: guest
     password: guest


rabbitmq:
  exchange: order-exchange
  routingkey: order-routing-key

#environment behaviors
feature-toggle:
  use-status-order-api: true
  use-payment-api: true
  kitchen-mq: true

external:
  payment-api:
    url: http://localhost:3000/api/initiatePayment
  status-order-api:
    url: http://external-status-api.com/status


