spring:
  application:
    name: status-order-consumer
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: order-finished
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    topic:
      name: order-finished-topic

server:
  port: 8084